routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

Route::get('/directroy/files', 'DirectoryController@directoryFiles');
Route::get('/directory/file/show/{id}', 'DirectoryController@directoryFileShow');
Route::post('file/comment', 'FileController@fileComment');

Route::group(['middleware' => ['auth', 'authorize']], function () {

    Route::get('/', 'PublicController@index');
    Route::get('/single/{file}', 'PublicController@singlePage')->name('singlePage');
    Route::get('/details/{id}', 'PublicController@listPage')->name('listPage');
    Route::get('/tag/{tag}', 'PublicController@listPage')->name('listPageTag');
    Route::post('/content/{id}', 'CommentController')->name('comment');
    Route::get('/video', 'PublicController@videoPage')->name('videoPage');
    Route::get('/video/{video}', 'PublicController@videoDetails')->name('videoDetails');


    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/users/{user}/profile', 'ShowProfile')->name('users.profile');
    Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
    Route::get('/categories/trash/{id}/restore', 'CategoryController@restore')->name('categories.restore');
    Route::delete('/categories/trash/{id}/delete', 'CategoryController@delete')->name('categories.delete');
    Route::resource('/categories', 'CategoryController');
    Route::resource('/directories', 'DirectoryController');
    Route::get('/user/direcotroy', 'DirectoryController@userDirectoryFile');

    Route::resource('/videos', 'VideoController');
    Route::resource('/posts', 'PostController');
    Route::resource('/files', 'FileController');
    Route::resource('/tags', 'TagController');
    //Route::get('/categories', 'CategoryController@index')->name('categories.index');
    //Route::get('/categories/create', 'CategoryController@create')->name('categories.create');
    //Route::post('/categories', 'CategoryController@store')->name('categories.store');
    //Route::get('/categories/{category}/edit', 'CategoryController@edit')->name('categories.edit');
    //Route::put('/categories/{category}', 'CategoryController@update')->name('categories.update');
    //Route::get('/categories/{category}', 'CategoryController@show')->name('categories.show');
    //Route::delete('/categories/{category}', 'CategoryController@destroy')->name('categories.destroy');
});

Route::post('/note/store/', 'NoteController@store')->name('note');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title',
        'category_id',
        'description',
        'image',
        'created_by',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

//    public function tags()
//    {
//        return $this->belongsToMany(Tag::class);
//    }

    public function tags()
    {
        return $this->morphToMany(Tag::class, 'taggable');
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable')->orderBy('created_at', 'desc');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\PostRequest;
use App\Post;
use App\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Image;


class PostController extends Controller
{

//    public function __construct()
//    {
//        $this->middleware('CheckCountry')->except('show');
//    }


    const UPLOAD_DIR = '/uploads/posts/';

    public function index()
    {
        $paginatePerPage = 5;
        $pageNumber = request('page');

        if(!is_null($pageNumber)){
            $serial = $paginatePerPage * $pageNumber - $paginatePerPage;
        }else{
            $serial = 0;
        }

        $keyword = request('keyword');
        if(!is_null($keyword)){
            $posts = Post::latest()->where('title', 'Like', "%{$keyword}%")->paginate($paginatePerPage);
        }else{
            $posts = Post::latest()->paginate($paginatePerPage);
        }

        return view('backend.posts.index', compact('posts', 'serial'));
//        return view('backend.posts.index', ['posts' => $posts]);
    }

    public function create()
    {
        $categories = Category::pluck('title', 'id');
        $tags = Tag::get(['title', 'id']);
        $selectedTags = [];
        return view('backend.posts.create', compact('categories', 'tags', 'selectedTags'));
    }

    public function store(PostRequest $request)
    {

//        $category = Category::findOrFail($request->category_id);

        $data = $request->except('image');
        $data['created_by'] = auth()->user()->id;
        if($request->hasFile('image')){
            $data['image'] = $this->uploadImage($request->image);
        }

//        $post = $category->posts()->create($data);
        $post = Post::create($data);

        $post->tags()->attach($request->tag_ids);

        Session::flash('message', 'Created Successfully');

        return redirect()->route('posts.index');
    }

    public function show(Post $post)//dependency injection or route model binding
    {

        return view('backend.posts.show', compact('post'));
    }

    public function edit(Post $post)
    {
        $categories = Category::pluck('title', 'id');
        $tags = Tag::get(['title', 'id']);
        $selectedTags = $post->tags()->pluck('title', 'id')->toArray();
        return view('backend.posts.edit', compact('post', 'categories', 'tags', 'selectedTags'));
    }

    public function update(PostRequest $request, Post $post)
    {
//        $post = Post::findOrFail($id);

        $data = $request->except('image');
        $data['updated_by'] = auth()->user()->id;
        if($request->hasFile('image')){
            $data['image'] = $this->uploadImage($request->image);
        }

        $post->update($data);

        $post->tags()->sync($request->tag_ids);

        Session::flash('message', 'Updated Successfully');
        return redirect()->route('posts.index');
    }

    public function destroy(Post $post)
    {
//        Post::destroy($id);
        $this->unlink($post->image);

        $post->tags()->detach();

        $post->delete();

        Session::flash('message', 'Deleted Successfully');
        return redirect()->route('posts.index');
//        return redirect()->route('backend.posts.index')->withMessage('Deleted Successfully !');
    }

    public function trash()
    {
        $posts = Post::onlyTrashed()->paginate(5);
        return view('backend.posts.trash', compact('posts'));
    }

    public function restore($id)
    {
        $post = Post::onlyTrashed()
            ->where('id', $id)
            ->first();

        $post->restore();
        Session::flash('message', 'Restored Successfully');
        return redirect()->back();
    }

    public function delete($id)
    {
        $post = Post::onlyTrashed()
                ->where('id', $id)
                ->first();
        $post->forceDelete();
        Session::flash('message', 'Delete Successfully');
        return redirect()->back();
    }

    private function uploadImage($file)
    {
        $timestamp = str_replace([' ', ':'], '-', Carbon::now()->toDateTimeString());//formatting the name for unique and readable
        $file_name =  $timestamp.'.'.$file->getClientOriginalExtension();
        Image::make($file)->resize(750, 300)->save(public_path() . self::UPLOAD_DIR . $file_name);
        return $file_name;
    }

    private function unlink($file)
    {
        if ($file != '' && file_exists(public_path() . self::UPLOAD_DIR . $file)) {
            @unlink(public_path() . self::UPLOAD_DIR . $file);
        }
    }

}

resources/views/backend/posts/create.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="card">
    <div class="card-header">
        <div class="float-left">
            Create Post
        </div>
        <div class="float-right">
            <a href="{{ route('posts.index') }}" class="btn btn-primary">List</a>
        </div>
    </div>
    <div class="card-body">

        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif

        {{--    <form action="{{ route('posts.store') }}" method="post">--}}
        {!! Form::open(['route' => 'posts.store', 'files' => true]) !!}
        {{--@csrf--}}

            {{--<input type="text" name="title" required placeholder="Enter Category Title Here"><br>--}}
        @include('backend.posts.form')
        <div class="form-group row">
            <div class="col-sm-10 text-center">
                {!! Form::button('Add', [
                                            'class' => 'btn btn-primary',
                                            'type' => 'submit',
                                        ]) !!}
            </div>
        </div>
        {!! Form::close() !!}
        {{--</form>--}}
    </div>
</div>
@endsection

resources/views/backend/posts/edit.blade.php
@extends('backend.layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="float-left">
                Edit Post
            </div>
            <div class="float-right">
                <a href="{{ route('posts.index') }}" class="btn btn-primary">List</a>
            </div>
        </div>
        <div class="card-body">

            @if ($errors->any())
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif
            {!! Form::model($post,[
                        'route' => ['posts.update', $post->id],
                        'method' => 'put',
                        'files' => true,
                        ]) !!}
            <fieldset>
                <legend>Edit Post</legend>
                    @include('backend.posts.form')
                <div class="form-group row">
                    <div class="col-sm-10 text-center">
                        {!! Form::button('Update', [
                                                    'class' => 'btn btn-primary',
                                                    'type' => 'submit',
                                                ]) !!}
                    </div>
                </div>
            </fieldset>
            {!! Form::close() !!}
                {{--</form>--}}
        </div>
    </div>
@endsection

resources/views/backend/posts/form.blade.php
<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('Title', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::text('title', null, [
                'class' => 'form-control',
                'id' => 'Title',
            ]) !!}<br>
        @if ($errors->has('title'))
            {{ $errors->first('title') }}
        @endif
    </div>
</div>

<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('category_id', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::select('category_id', $categories, null, [
                'placeholder' => 'Select Category',
                'class' => 'form-control',
                'id' => 'category_id',
            ]) !!}<br>
        @if ($errors->has('category_id'))
            {{ $errors->first('category_id') }}
        @endif
    </div>
</div>

<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('description', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::textarea('description', null, [
                'class' => 'form-control',
                'id' => 'description',
            ]) !!}<br>
        @if ($errors->has('description'))
            {{ $errors->first('description') }}
        @endif
    </div>
</div>

<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('image', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::file('image', [
                'class' => 'form-control',
                'id' => 'image',
            ]) !!}<br>
        @if ($errors->has('image'))
            {{ $errors->first('image') }}
        @endif
    </div>
</div>


<div class="form-group row">
    {!! Form::label('tag_id', 'Tags', ["class" => "col-md-2 col-form-label text-md-right"]) !!}
    <div class="col-md-10">
        @foreach ($tags as $tag)
            <div class="checkbox">
                <label>
                    {{ Form::checkbox('tag_ids[]', $tag->id, in_array($tag->title, $selectedTags), ['class' => 'field']) }}
                    {{ $tag->title }}
                </label>
            </div>
        @endforeach
    </div>
</div>


{{--in_array($tag->id, $selectedTagIds--}}


@push('scripts')
    <script src="//cdn.ckeditor.com/4.5.11/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('description', {
            uiColor: '#9AB8F3'
        });
    </script>
@endpush

resources/views/backend/posts/index.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="card">
    <div class="card-header">
        <div class="float-left">
            Posts
        </div>
        <div class="float-right">
{{--            <a href="{{ route('posts.trash') }}" class="btn btn-primary">Trash</a>--}}
            <a href="{{ route('posts.create') }}" class="btn btn-primary">Add New</a>
        </div>
    </div>
    <div class="card-body">
        {!! Form::open(['route' => 'posts.index', 'method'=>'GET']) !!}
            <div class="input-group mb-2 mr-sm-2">
                {!! Form::text('keyword', null ,[
                                                    'class' => 'form-control'
                                                ]) !!}
                {{--<input type="text" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Username" required="">--}}
                <div class="input-group-append">
                    <div class="input-group-text">{{ Form::button('<i class="fa fa-search"></i>', ['type' => 'submit']) }}</div>
                </div>
            </div>
        {!! Form::close() !!}

        @include('backend.layouts.elements.error')

        <table class="table table-bordered table-striped">
            <tr>
                <th width="100">SL#</th>
                <th>Title</th>
                <th width="200" class="text-right">Action</th>
            </tr>
            @foreach($posts as $post)
                <tr>
                    <td>{{ ++$serial }}</td>
                    <td>{{ $post->title }}</td>
                    <td class="text-right">
                        <a href="{{ route('posts.show', $post->id) }}" class="btn btn-sm btn-primary">Show</a>
                        <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-sm btn-warning">Edit</a>
                        {{--                    <a href="{{ route('posts.destroy', $post->id) }}">--}}


                        {!! Form::open([
                                        'route' => ['posts.destroy', $post->id],
                                        'method' => 'delete',
                                        'style' => 'display:inline',
                                    ]) !!}
                        {!! Form::button('Delete',[
                                'type' => 'submit',
                                'class' => "btn btn-sm btn-danger",
                                'onclick' => 'return confirm("Are You Sure Want To Delete ?")',

                        ]) !!}
                        {!! Form::close() !!}


                        {{--</a>--}}
                    </td>
                </tr>
            @endforeach
        </table>
        <div class="float-right">
            {{ $posts->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/backend/posts/show.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="card">
    <div class="card-header">

        <div class="float-left">
            Post Details
        </div>

        <div class="float-right">
            <a href="{{ route('posts.index') }}" class="btn btn-primary">List</a>
        </div>

    </div>
    <div class="card-body">

        <table class="table table-bordered table-striped">

            <tr>
                <td>Title</td>
                <td>{{ $post->title }}</td>
            </tr>

            <tr>
                <td>Category</td>
                <td>{{ $post->category->title }}</td>
            </tr>

            <tr>
                <td>Image</td>
                <td><img src="{{ asset('/uploads/posts/'. $post->image) }}" alt=""></td>
            </tr>
            
            <tr>
                <td>Description</td>
                <td>{!! $post->description !!}</td>
            </tr>

            <tr>
                <td>Tags</td>
                <td>
                    @foreach($post->tags as $tag)
                        <a href="#">{{ $tag->title }}</a> |
                    @endforeach
                </td>
            </tr>

            <tr>
                <td>Created At</td>
                <td>{{ $post->created_at }}</td>
            </tr>

            <tr>
                <td>Created By</td>
                <td>{{ $post->creator->name }}</td>
            </tr>

        </table>

    </div>
</div>
@endsection

resources/views/backend/posts/trash.blade.php
@extends('backend.layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="float-left">
                Deleted Categories
            </div>
            <div class="float-right">
                <a href="{{ route('categories.index') }}" class="btn btn-primary">List</a>
            </div>
        </div>
        <div class="card-body">

            @if (session()->has('message'))
                {{ session('message') }}
            @endif
            <table class="table table-bordered table-striped">
                <tr>
                    <th width="100">SL#</th>
                    <th>Title</th>
                    <th width="220" class="text-right">Action</th>
                </tr>
                @php $serial = 0; @endphp
                @foreach($categories as $category)
                    <tr>
                        <td>{{ ++$serial }}</td>
                        <td>{{ $category->title }}</td>
                        <td class="text-right">
                            <a href="{{ route('categories.show', $category->id) }}" class="btn btn-sm btn-primary">Show</a>
                            <a href="{{ route('categories.restore', $category->id) }}" class="btn btn-sm btn-warning">Restore</a>
                            {!! Form::open([
                                            'route' => ['categories.delete', $category->id],
                                            'method' => 'delete',
                                            'style' => 'display:inline',
                                        ]) !!}
                            {!! Form::button('Delete',[
                                    'type' => 'submit',
                                    'class' => "btn btn-sm btn-danger",
                                    'onclick' => 'return confirm("Are You Sure Want To Delete Permanently ?")',

                            ]) !!}
                            {!! Form::close() !!}
                            {{--</a>--}}
                        </td>
                    </tr>
                @endforeach
            </table>
            <div class="float-right">
                {{ $categories->links() }}
            </div>
        </div>
    </div>
@endsection