routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

Route::get('/directroy/files', 'DirectoryController@directoryFiles');
Route::get('/directory/file/show/{id}', 'DirectoryController@directoryFileShow');
Route::post('file/comment', 'FileController@fileComment');

Route::group(['middleware' => ['auth', 'authorize']], function () {

    Route::get('/', 'PublicController@index');
    Route::get('/single/{file}', 'PublicController@singlePage')->name('singlePage');
    Route::get('/details/{id}', 'PublicController@listPage')->name('listPage');
    Route::get('/tag/{tag}', 'PublicController@listPage')->name('listPageTag');
    Route::post('/content/{id}', 'CommentController')->name('comment');
    Route::get('/video', 'PublicController@videoPage')->name('videoPage');
    Route::get('/video/{video}', 'PublicController@videoDetails')->name('videoDetails');


    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/users/{user}/profile', 'ShowProfile')->name('users.profile');
    Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
    Route::get('/categories/trash/{id}/restore', 'CategoryController@restore')->name('categories.restore');
    Route::delete('/categories/trash/{id}/delete', 'CategoryController@delete')->name('categories.delete');
    Route::resource('/categories', 'CategoryController');
    Route::resource('/directories', 'DirectoryController');
    Route::get('/user/direcotroy', 'DirectoryController@userDirectoryFile');

    Route::resource('/videos', 'VideoController');
    Route::resource('/posts', 'PostController');
    Route::resource('/files', 'FileController');
    Route::resource('/tags', 'TagController');
    //Route::get('/categories', 'CategoryController@index')->name('categories.index');
    //Route::get('/categories/create', 'CategoryController@create')->name('categories.create');
    //Route::post('/categories', 'CategoryController@store')->name('categories.store');
    //Route::get('/categories/{category}/edit', 'CategoryController@edit')->name('categories.edit');
    //Route::put('/categories/{category}', 'CategoryController@update')->name('categories.update');
    //Route::get('/categories/{category}', 'CategoryController@show')->name('categories.show');
    //Route::delete('/categories/{category}', 'CategoryController@destroy')->name('categories.destroy');
});

Route::post('/note/store/', 'NoteController@store')->name('note');

resources/views/backend/layouts/partials/footer.blade.php
{{--<div class="copyright-w3layouts py-xl-3 py-2 mt-xl-5 mt-4 text-center">--}}
    {{--<p>© 2018 E-Nothi . All Rights Reserved | Design & Developed by--}}
        {{--<a href="https://www.pondit.com"> Pondit </a>--}}
    {{--</p>--}}
{{--</div>--}}

resources/views/backend/layouts/partials/header.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: LAB-TRAINER
 * Date: 10/3/2018
 * Time: 8:42 PM
 */

resources/views/backend/layouts/partials/sidebar.blade.php
<div class="sidebar-header">
    <h1>
        <a href="{{ url('/home') }}">{{ config('app.name') }}</a>
    </h1>
    <span>E</span>
</div>
<div class="profile-bg"></div>
<ul class="list-unstyled components">
    <li class="active">
        <a href="{{ url('/home') }}">
            <i class="fas fa-th-large"></i>
            Dashboard
        </a>
    </li>
    {{--<li>--}}
        {{--<a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">--}}
            {{--<i class="fas fa-laptop"></i>--}}
            {{--Categories--}}
            {{--<i class="fas fa-angle-down fa-pull-right"></i>--}}
        {{--</a>--}}
        {{--<ul class="collapse list-unstyled" id="homeSubmenu">--}}
            {{--<li>--}}
                {{--<a href="{{ route('categories.create') }}">Add</a>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<a href="{{ route('categories.index') }}">List</a>--}}
            {{--</li>--}}
        {{--</ul>--}}
    {{--</li>--}}
    <li>
        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">
            <i class="fas fa-laptop"></i>
            Directories
            <i class="fas fa-angle-down fa-pull-right"></i>
        </a>
        <ul class="collapse list-unstyled" id="homeSubmenu">
            <li>
                <a href="{{ route('directories.create') }}">Add</a>
            </li>
            <li>
                <a href="{{ route('directories.index') }}">List</a>
            </li>
        </ul>
    </li>

    {{--<li>--}}
        {{--<a href="#tags" data-toggle="collapse" aria-expanded="false">--}}
            {{--<i class="fas fa-laptop"></i>--}}
            {{--Tags--}}
            {{--<i class="fas fa-angle-down fa-pull-right"></i>--}}
        {{--</a>--}}
        {{--<ul class="collapse list-unstyled" id="tags">--}}
            {{--<li>--}}
                {{--<a href="{{ route('tags.create') }}">Add</a>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<a href="{{ route('tags.index') }}">List</a>--}}
            {{--</li>--}}
        {{--</ul>--}}
    {{--</li>--}}

    {{--<li>--}}
        {{--<a href="#posts" data-toggle="collapse" aria-expanded="false">--}}
            {{--<i class="fas fa-laptop"></i>--}}
            {{--Posts--}}
            {{--<i class="fas fa-angle-down fa-pull-right"></i>--}}
        {{--</a>--}}
        {{--<ul class="collapse list-unstyled" id="posts">--}}
            {{--<li>--}}
                {{--<a href="{{ route('posts.create') }}">Add</a>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<a href="{{ route('posts.index') }}">List</a>--}}
            {{--</li>--}}
        {{--</ul>--}}
    {{--</li>--}}
    <li>
        <a href="#files" data-toggle="collapse" aria-expanded="false">
            <i class="fas fa-laptop"></i>
            Files
            <i class="fas fa-angle-down fa-pull-right"></i>
        </a>
        <ul class="collapse list-unstyled" id="files">
            <li>
                <a href="{{ route('files.create') }}">Add</a>
            </li>
            <li>
                <a href="{{ route('files.index') }}">List</a>
            </li>
        </ul>
    </li>
    {{--<li>--}}
        {{--<a href="#videos" data-toggle="collapse" aria-expanded="false">--}}
            {{--<i class="fas fa-laptop"></i>--}}
            {{--Videos--}}
            {{--<i class="fas fa-angle-down fa-pull-right"></i>--}}
        {{--</a>--}}
        {{--<ul class="collapse list-unstyled" id="videos">--}}
            {{--<li>--}}
                {{--<a href="{{ route('videos.create') }}">Add</a>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<a href="{{ route('videos.index') }}">List</a>--}}
            {{--</li>--}}
        {{--</ul>--}}
    {{--</li>--}}

</ul>